using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BusinessEntities.EntityClasses
{
    public class VillageInfoEntities
    {
        public int VillageID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> DistID { get; set; }
        public Nullable<int> SubDistID { get; set; }
        public string CdBCode { get; set; }
        public string VILLAGE { get; set; }
        public string VillageNameWithDistrict
        {
            get
            {
                return VILLAGE + " " + "||" + " " + CDBLOCKN;
            }
        }
        public string CDBLOCKN { get; set; }

        //public string GrmCode { get; set; }
        //public string GMPNAME { get; set; }
        //public Nullable<int> Year { get; set; }
        //public string SDHQNAME { get; set; }
        //public Nullable<int> SUBDISTHQD { get; set; }
        //public string DSTHQNAME { get; set; }
        //public Nullable<int> DHQDISTKM { get; set; }
        //public string NRSTOWN { get; set; }
        //public Nullable<int> NRSTOWNKM { get; set; }
        //public string WSUTn { get; set; }
        //public Nullable<int> WSUTd { get; set; }
        //public Nullable<int> TTLAREAH { get; set; }
        //public Nullable<int> TTLHOUSEV { get; set; }
        //public string TTLPOPUV { get; set; }
        //public Nullable<int> TTLMALEV { get; set; }
        //public Nullable<int> TTLFMALEV { get; set; }
        //public Nullable<int> TTLSCPOPV { get; set; }
        //public Nullable<double> TTLSCMALV { get; set; }
        //public Nullable<double> TTLSCFMLV { get; set; }
        //public Nullable<double> TTLSTPOPV { get; set; }
        //public Nullable<double> TTLSTMALV { get; set; }
        //public Nullable<double> TTLSTFMLV { get; set; }
        //public Nullable<double> GPSS { get; set; }
        //public Nullable<double> GPRSCHN { get; set; }
        //public Nullable<double> PPSS { get; set; }
        //public Nullable<double> PRPVTSCLN { get; set; }
        //public string GMSS { get; set; }
        //public Nullable<double> GMSCHOOLN { get; set; }
        //public Nullable<double> PMSS { get; set; }
        //public Nullable<double> PVMSCHOOLN { get; set; }
        //public string GSSS { get; set; }
        //public Nullable<double> GSSCHOOLN { get; set; }
        //public Nullable<double> PSSS { get; set; }
        //public Nullable<double> SECPVTSCLN { get; set; }
        //public Nullable<double> GSSSS { get; set; }
        //public Nullable<double> GSSSN { get; set; }
        //public Nullable<double> PSSSS { get; set; }
        //public Nullable<double> PSSSN { get; set; }
        //public Nullable<double> NFSG { get; set; }
        //public Nullable<double> GASDCLGST { get; set; }
        //public Nullable<double> GASDCLGN { get; set; }
        //public Nullable<double> PASDCS { get; set; }
        //public Nullable<double> PASDCN { get; set; }
        //public Nullable<double> GECS { get; set; }
        //public Nullable<double> GECN { get; set; }
        //public Nullable<double> PECS { get; set; }
        //public Nullable<double> PECN { get; set; }
        //public Nullable<double> GPS { get; set; }
        //public Nullable<double> GOVPOLYTN { get; set; }
        //public Nullable<double> PPS { get; set; }
        //public Nullable<double> PVTPOLYTN { get; set; }
        //public Nullable<double> GVTSS { get; set; }
        //public Nullable<double> GVTSSN { get; set; }
        //public Nullable<double> PVTSS { get; set; }
        //public Nullable<double> PVTSN { get; set; }
        //public Nullable<double> CHLTCDRSR { get; set; }
        //public Nullable<double> CHCDIPN { get; set; }
        //public Nullable<double> CHCPMSTSN { get; set; }
        //public Nullable<double> CHCPMSIPN { get; set; }
        //public Nullable<double> PRHLTHCLN { get; set; }
        //public Nullable<double> PHCDTSN { get; set; }
        //public Nullable<double> PHCDPN { get; set; }
        //public Nullable<double> PHCPMSTSN { get; set; }
        //public Nullable<double> PHCPMSPN { get; set; }
        //public Nullable<double> PHLTSCN { get; set; }
        //public Nullable<double> PHSCDTSN { get; set; }
        //public Nullable<double> PHSCDPN { get; set; }
        //public Nullable<double> PHSCPMSTSN { get; set; }
        //public Nullable<double> PHSCPMSPN { get; set; }
        //public Nullable<double> HOSALOPN { get; set; }
        //public Nullable<double> HADTSN { get; set; }
        //public Nullable<double> HADPN { get; set; }
        //public Nullable<double> HAPMSTSN { get; set; }
        //public Nullable<double> HAPMSIPN { get; set; }
        //public Nullable<double> DISPENSRN { get; set; }
        //public Nullable<double> DDTSN { get; set; }
        //public Nullable<double> DDPN { get; set; }
        //public Nullable<double> VETHOSN { get; set; }
        //public Nullable<double> VETHOSDST { get; set; }
        //public Nullable<double> VETHOSPST { get; set; }
        //public Nullable<double> VHDPN { get; set; }
        //public Nullable<double> VHPMSPN { get; set; }
        //public Nullable<double> FMLWARECN { get; set; }
        //public Nullable<double> FWCDTSN { get; set; }
        //public Nullable<double> FWCDPN { get; set; }
        //public Nullable<double> FWCPMSTSN { get; set; }
        //public Nullable<double> FWCPMSPN { get; set; }
        //public Nullable<double> TWTS { get; set; }
        //public Nullable<double> CVRWELLST { get; set; }
        //public string CWFRYS { get; set; }
        //public string CWFSMAS { get; set; }
        //public Nullable<double> UWS { get; set; }
        //public string UWFRS { get; set; }
        //public string UWFSMS { get; set; }
        //public Nullable<double> TWELLST { get; set; }
        //public Nullable<double> SPRINGST { get; set; }
        //public string TWELLYR { get; set; }
        //public string TWBFSMAS { get; set; }
        //public Nullable<double> RCS { get; set; }
        //public string SFRYS { get; set; }
        //public string SFSMASS { get; set; }
        //public string RIVRCNLYR { get; set; }
        //public string RIVRCNLSM { get; set; }
        //public Nullable<double> TANKPLST { get; set; }
        //public string TANKPLYR { get; set; }
        //public string TPLFS { get; set; }
        //public Nullable<double> OS { get; set; }
        //public Nullable<double> CDRNGST { get; set; }
        //public string OFSA { get; set; }
        //public string OFSMA { get; set; }
        //public Nullable<double> OPDRNGST { get; set; }
        //public Nullable<double> NDRNGST { get; set; }
        //public Nullable<double> OKDS { get; set; }
        //public Nullable<double> OPDCTSS { get; set; }
        //public Nullable<double> OPDUSA { get; set; }
        //public Nullable<double> CWDSAHHCS { get; set; }
        //public Nullable<double> CBGRWPS { get; set; }
        //public Nullable<double> POSTOFICE { get; set; }
        //public string POSTOFFDS { get; set; }
        //public Nullable<double> SPOSTOFFC { get; set; }
        //public string C5Km510Kms2 { get; set; }
        //public Nullable<double> VPINCODST { get; set; }
        //public string VPINCODDS { get; set; }
        //public Nullable<double> PINCODE { get; set; }
        //public string TELLNDLDS { get; set; }
        //public Nullable<double> TELLNDLST { get; set; }
        //public Nullable<double> PCOMPCOST { get; set; }
        //public string C5Km510Kms5 { get; set; }
        //public Nullable<double> MOBLCOVDS { get; set; }
        //public string C5Km510Kms6 { get; set; }
        //public Nullable<double> ICCSCS { get; set; }
        //public string C5Km510Kms7 { get; set; }
        //public Nullable<double> PCOURERST { get; set; }
        //public string PCOURERDS { get; set; }
        //public Nullable<double> PBUSSERST { get; set; }
        //public string PBUSSERDS { get; set; }
        //public Nullable<double> PVTBUSSST { get; set; }
        //public string PVTBUSSDT { get; set; }
        //public Nullable<double> RAILSTST { get; set; }
        //public string RAILSTDT { get; set; }
        //public Nullable<double> AMAS { get; set; }
        //public string C5Km510Kms12 { get; set; }
        //public Nullable<double> TAXISTATUS { get; set; }
        //public string C5Km510Kms13 { get; set; }
        //public Nullable<double> VANSSTATUS { get; set; }
        //public string C5Km510Kms14 { get; set; }
        //public Nullable<double> TRACTORST { get; set; }
        //public string TRACTORDT { get; set; }
        //public Nullable<double> CARTSDAST { get; set; }
        //public string C5Km510Kms16 { get; set; }
        //public Nullable<double> NHIGHWAYS { get; set; }
        //public string NHIGHWAYD { get; set; }
        //public Nullable<double> STATHIWYS { get; set; }
        //public string STATHIWYD { get; set; }
        //public Nullable<double> MJDIROADS { get; set; }
        //public string MJDIROADD { get; set; }
        //public Nullable<double> ODRS { get; set; }
        //public string C5Km510Kms20 { get; set; }
        //public Nullable<double> BTRS { get; set; }
        //public string C5Km510Kms21 { get; set; }
        //public Nullable<double> GRS { get; set; }
        //public string C5Km510Kms22 { get; set; }
        //public string ATMDISTANC { get; set; }
        //public Nullable<double> ATMSTATUS { get; set; }
        //public Nullable<double> COMBANKST { get; set; }
        //public string COMBANKDT { get; set; }
        //public Nullable<double> COOPBNKST { get; set; }
        //public string COOPBNKDT { get; set; }
        //public Nullable<double> AGCRDTSOCS { get; set; }
        //public string AGCRDTSOCD { get; set; }
        //public Nullable<double> SHGRUPST { get; set; }
        //public string SHGRUPDT { get; set; }
        //public Nullable<double> PDSSHOPST { get; set; }
        //public string PDSSHOPDT { get; set; }
        //public Nullable<double> MANDIRMST { get; set; }
        //public string MANDIRMDT { get; set; }
        //public Nullable<double> WKLYHATST { get; set; }
        //public string WKLYHATDT { get; set; }
        //public Nullable<double> AGMKTSOCS { get; set; }
        //public string AGMKTSOCD { get; set; }
        //public Nullable<double> CVHS { get; set; }
        //public string C5Km510Kms31 { get; set; }
        //public Nullable<double> DLYNEWSPRS { get; set; }
        //public string C5Km510Kms32 { get; set; }
        //public Nullable<double> ASSPOLYSTS { get; set; }
        //public string ASSPOLYSTD { get; set; }
        //public Nullable<double> BIRTHDTRGS { get; set; }
        //public string BIRTHDTRGD { get; set; }
        //public Nullable<double> POWRSDSST { get; set; }
        //public Nullable<double> POWRSAGRI { get; set; }
        //public Nullable<double> PSDUSAS { get; set; }
        //public Nullable<double> PSDUWOM { get; set; }
        //public Nullable<double> PSASAS1 { get; set; }
        //public Nullable<double> PSAWOM1 { get; set; }
        //public Nullable<double> POWRSCOMM { get; set; }
        //public Nullable<double> PSAWOM2 { get; set; }
        //public Nullable<double> PSCSAS2 { get; set; }
        //public Nullable<double> PSFAU { get; set; }
        //public string AGRICOMM1 { get; set; }
        //public Nullable<double> PSUSAS { get; set; }
        //public Nullable<double> PSUSOM { get; set; }
        //public string MCF { get; set; }
        //public string HCF { get; set; }
        //public string AGRICOMM2 { get; set; }
        //public string MCS { get; set; }
        //public string HCS { get; set; }
        //public string AGRICOMM3 { get; set; }
        //public string MCT { get; set; }
        //public string HCT { get; set; }
        //public Nullable<double> FORESTAREA { get; set; }
        //public Nullable<double> AREANONAG { get; set; }
        //public Nullable<double> BAUNCULTAR { get; set; }
        //public Nullable<double> PPASTURGZ { get; set; }
        //public Nullable<double> MSTREECROP { get; set; }
        //public Nullable<double> CULWSTLAND { get; set; }
        //public Nullable<double> CURRNTFALO { get; set; }
        //public Nullable<double> FALOLND { get; set; }
        //public Nullable<double> ARIRRIBYSO { get; set; }
        //public Nullable<double> NETARSOWN { get; set; }
        //public Nullable<double> TTLUNIRRIG { get; set; }
        //public Nullable<double> CANALAREA { get; set; }
        //public Nullable<double> WELLAREA { get; set; }
        //public Nullable<double> TANKLAKEAR { get; set; }
        //public Nullable<double> WATERFALAR { get; set; }
        //public Nullable<double> OTRSOURCE { get; set; }
        //public string NRTOWNNAME { get; set; }
        //public Nullable<double> NRTWNDIST { get; set; }

    }
}
