//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropResultInfo
    {
        public int CropResultID { get; set; }
        public int CropID { get; set; }
        public string Result { get; set; }
    
        public virtual CropInfo CropInfo { get; set; }
    }
}
