//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBentities : DbContext
    {
        public DBentities()
            : base("name=DBentities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CropInfo> CropInfoes { get; set; }
        public virtual DbSet<CropResultInfo> CropResultInfoes { get; set; }
        public virtual DbSet<DealerDetail> DealerDetails { get; set; }
        public virtual DbSet<DelerAddInfo> DelerAddInfoes { get; set; }
        public virtual DbSet<DelerBankInfo> DelerBankInfoes { get; set; }
        public virtual DbSet<DelerInfo> DelerInfoes { get; set; }
        public virtual DbSet<DelerLicencesInfo> DelerLicencesInfoes { get; set; }
        public virtual DbSet<DelerPartenarInfo> DelerPartenarInfoes { get; set; }
        public virtual DbSet<DelerType> DelerTypes { get; set; }
        public virtual DbSet<DistrictInfo> DistrictInfoes { get; set; }
        public virtual DbSet<FAaddressDetail> FAaddressDetails { get; set; }
        public virtual DbSet<FAapproval> FAapprovals { get; set; }
        public virtual DbSet<FAapprovedBy> FAapprovedBies { get; set; }
        public virtual DbSet<FAdesignation> FAdesignations { get; set; }
        public virtual DbSet<FAdetail> FAdetails { get; set; }
        public virtual DbSet<FAdocumentType> FAdocumentTypes { get; set; }
        public virtual DbSet<FAeducationDetail> FAeducationDetails { get; set; }
        public virtual DbSet<FAexperianceDetail> FAexperianceDetails { get; set; }
        public virtual DbSet<FApaymentAgency> FApaymentAgencies { get; set; }
        public virtual DbSet<FarmerConsumption> FarmerConsumptions { get; set; }
        public virtual DbSet<FarmerConsumptionMapping> FarmerConsumptionMappings { get; set; }
        public virtual DbSet<FarmerCropsMapping> FarmerCropsMappings { get; set; }
        public virtual DbSet<FarmerDealerMapping> FarmerDealerMappings { get; set; }
        public virtual DbSet<FarmerDetail> FarmerDetails { get; set; }
        public virtual DbSet<FarmerInputSourceMapping> FarmerInputSourceMappings { get; set; }
        public virtual DbSet<FarmerLandMapping> FarmerLandMappings { get; set; }
        public virtual DbSet<FarmerLandType> FarmerLandTypes { get; set; }
        public virtual DbSet<FarmerPesticesMapping> FarmerPesticesMappings { get; set; }
        public virtual DbSet<FarmerPesticideType> FarmerPesticideTypes { get; set; }
        public virtual DbSet<FarmerTypeDetail> FarmerTypeDetails { get; set; }
        public virtual DbSet<FAStatu> FAStatus { get; set; }
        public virtual DbSet<FAtargetDetail> FAtargetDetails { get; set; }
        public virtual DbSet<FAtargetVillageMapping> FAtargetVillageMappings { get; set; }
        public virtual DbSet<FAuploadedDocumentDetail> FAuploadedDocumentDetails { get; set; }
        public virtual DbSet<FertilizerInfo> FertilizerInfoes { get; set; }
        public virtual DbSet<GroupInfo> GroupInfoes { get; set; }
        public virtual DbSet<InputSource> InputSources { get; set; }
        public virtual DbSet<IrrigationSource> IrrigationSources { get; set; }
        public virtual DbSet<LandOwnershipType> LandOwnershipTypes { get; set; }
        public virtual DbSet<PesticesInfo> PesticesInfoes { get; set; }
        public virtual DbSet<Pesticide> Pesticides { get; set; }
        public virtual DbSet<PestiesUnit> PestiesUnits { get; set; }
        public virtual DbSet<PocketCropMapping> PocketCropMappings { get; set; }
        public virtual DbSet<PocketFertilizerMapping> PocketFertilizerMappings { get; set; }
        public virtual DbSet<PocketInfo> PocketInfoes { get; set; }
        public virtual DbSet<PocketStatu> PocketStatus { get; set; }
        public virtual DbSet<PocketVillageMapping> PocketVillageMappings { get; set; }
        public virtual DbSet<ProjectException> ProjectExceptions { get; set; }
        public virtual DbSet<SaDetail> SaDetails { get; set; }
        public virtual DbSet<StateInfo> StateInfoes { get; set; }
        public virtual DbSet<SubDistrictInfo> SubDistrictInfoes { get; set; }
        public virtual DbSet<TODO> TODOes { get; set; }
        public virtual DbSet<UserGroupInfo> UserGroupInfoes { get; set; }
        public virtual DbSet<UserInformation> UserInformations { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<VillageInfo> VillageInfoes { get; set; }
        public virtual DbSet<StateInformation> StateInformations { get; set; }
        public virtual DbSet<Structure> Structures { get; set; }
    }
}
