//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelerLicencesInfo
    {
        public int DelerLicencesInfoID { get; set; }
        public int DelerID { get; set; }
        public string InsecticideLicenceNo { get; set; }
        public System.DateTime InLicenceDateOfIssue { get; set; }
        public string InLicencePlaceOfIssue { get; set; }
        public string InLicenceIssuedBy { get; set; }
        public System.DateTime InLicenceValidupto { get; set; }
        public string FertilizerLicenceNo { get; set; }
        public System.DateTime FrLicenceDateOfIssue { get; set; }
        public string FrLicencePlaceOfIssue { get; set; }
        public string FrLicenceIssuedBy { get; set; }
        public System.DateTime FrLicenceValidupto { get; set; }
        public string CentralSalesTaxNo { get; set; }
        public System.DateTime CSTLicenceDateOfIssue { get; set; }
        public string CSTLicencePlaceOfIssue { get; set; }
        public string CSTLicenceIssuedBy { get; set; }
        public System.DateTime CSTLicenceValidupto { get; set; }
        public string StateSalesTaxNo { get; set; }
        public System.DateTime SSTLicenceDateOfIssue { get; set; }
        public string SSTLicencePlaceOfIssue { get; set; }
        public string SSTLicenceIssuedBy { get; set; }
        public System.DateTime SSTLicenceValidupto { get; set; }
    
        public virtual DelerInfo DelerInfo { get; set; }
    }
}
