//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelerPartenarInfo
    {
        public int DelerParternarID { get; set; }
        public int DelerID { get; set; }
        public string PartenarSurname1 { get; set; }
        public string PartenarFirstName1 { get; set; }
        public string PartenarMidName1 { get; set; }
        public string PartenarDesignation1 { get; set; }
        public string PartenarAddress1 { get; set; }
        public string PartenarSurname2 { get; set; }
        public string PartenarFirstName2 { get; set; }
        public string PartenarMidName2 { get; set; }
        public string PartenarDesignation2 { get; set; }
        public string PartenarAddres2 { get; set; }
        public string PartenarSurname3 { get; set; }
        public string PartenarFirstName3 { get; set; }
        public string PartenarMidName3 { get; set; }
        public string PartenarDesignation3 { get; set; }
        public string PartenarAddres3 { get; set; }
    
        public virtual DelerInfo DelerInfo { get; set; }
    }
}
