//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelerBankInfo
    {
        public int DelerBankInfoID { get; set; }
        public int DelerID { get; set; }
        public string Bank1Name { get; set; }
        public string Bank1ACNo { get; set; }
        public string Bank1FullAddress { get; set; }
        public string Bank1PhnNo { get; set; }
        public string Bank2Name { get; set; }
        public string Bank2ACNo { get; set; }
        public string Bank2FullAddress { get; set; }
        public string Bank2PhnNo { get; set; }
        public string TransporterName { get; set; }
        public string TransporterACNo { get; set; }
        public string TransporterFullAddress { get; set; }
        public string TransporterPhnNo { get; set; }
    
        public virtual DelerInfo DelerInfo { get; set; }
    }
}
