//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelerAddInfo
    {
        public int DelerAddID { get; set; }
        public int DelerID { get; set; }
        public string ShopAddress { get; set; }
        public string ShopPost { get; set; }
        public string ShopPincode { get; set; }
        public string ShopTaluka { get; set; }
        public int ShopDistrictID { get; set; }
        public int ShopStateID { get; set; }
        public string ShopTelNo { get; set; }
        public int ShopWkgHrs { get; set; }
        public string GodownAddress { get; set; }
        public string GodownPost { get; set; }
        public string GodownPincode { get; set; }
        public string GodownTaluka { get; set; }
        public int GodownDistrictID { get; set; }
        public int GodownStateID { get; set; }
        public string GodownTelNo { get; set; }
        public int GodownWkgHrs { get; set; }
        public string ResidanceAddress { get; set; }
        public string ResidancePost { get; set; }
        public string ResidancePincode { get; set; }
        public string ResidanceTaluka { get; set; }
        public int ResidanceDistrictID { get; set; }
        public int ResidanceStateID { get; set; }
        public string ResidanceTelNo { get; set; }
        public int ResidanceWkgHrs { get; set; }
    
        public virtual DelerInfo DelerInfo { get; set; }
        public virtual DistrictInfo DistrictInfo { get; set; }
        public virtual DistrictInfo DistrictInfo1 { get; set; }
        public virtual DistrictInfo DistrictInfo2 { get; set; }
        public virtual StateInfo StateInfo { get; set; }
        public virtual StateInfo StateInfo1 { get; set; }
        public virtual StateInfo StateInfo2 { get; set; }
    }
}
