//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistrictInfo()
        {
            this.DelerAddInfoes = new HashSet<DelerAddInfo>();
            this.DelerAddInfoes1 = new HashSet<DelerAddInfo>();
            this.DelerAddInfoes2 = new HashSet<DelerAddInfo>();
            this.FAaddressDetails = new HashSet<FAaddressDetail>();
            this.PocketInfoes = new HashSet<PocketInfo>();
            this.SubDistrictInfoes = new HashSet<SubDistrictInfo>();
            this.VillageInfoes = new HashSet<VillageInfo>();
        }
    
        public int DistID { get; set; }
        public int StateID { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DelerAddInfo> DelerAddInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DelerAddInfo> DelerAddInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DelerAddInfo> DelerAddInfoes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAaddressDetail> FAaddressDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PocketInfo> PocketInfoes { get; set; }
        public virtual StateInfo StateInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubDistrictInfo> SubDistrictInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VillageInfo> VillageInfoes { get; set; }
    }
}
