//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAdetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAdetail()
        {
            this.FAaddressDetails = new HashSet<FAaddressDetail>();
            this.FAapprovals = new HashSet<FAapproval>();
            this.FAeducationDetails = new HashSet<FAeducationDetail>();
            this.FAexperianceDetails = new HashSet<FAexperianceDetail>();
            this.FAtargetDetails = new HashSet<FAtargetDetail>();
            this.FAuploadedDocumentDetails = new HashSet<FAuploadedDocumentDetail>();
        }
    
        public int Id { get; set; }
        public string FormNo { get; set; }
        public Nullable<System.DateTime> EnrollDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FAname { get; set; }
        public Nullable<int> FAdesignationId { get; set; }
        public Nullable<bool> IsExperienced { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAaddressDetail> FAaddressDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAapproval> FAapprovals { get; set; }
        public virtual FAdesignation FAdesignation { get; set; }
        public virtual FAStatu FAStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAeducationDetail> FAeducationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAexperianceDetail> FAexperianceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAtargetDetail> FAtargetDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAuploadedDocumentDetail> FAuploadedDocumentDetails { get; set; }
    }
}
