//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAeducationDetail
    {
        public int Id { get; set; }
        public Nullable<int> FAid { get; set; }
        public string Examination { get; set; }
        public string University { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string Grade { get; set; }
        public string Subjects { get; set; }
    
        public virtual FAdetail FAdetail { get; set; }
    }
}
