//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerPesticesMapping
    {
        public int id { get; set; }
        public Nullable<int> farmerId { get; set; }
        public Nullable<int> PesticesTyepId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string PesticeName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual FarmerDetail FarmerDetail { get; set; }
        public virtual FarmerPesticideType FarmerPesticideType { get; set; }
        public virtual PestiesUnit PestiesUnit { get; set; }
    }
}
