//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerInputSourceMapping
    {
        public int Id { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public Nullable<int> InputSourceId { get; set; }
        public Nullable<int> DealerId { get; set; }
        public Nullable<int> VillageId { get; set; }
    
        public virtual DelerInfo DelerInfo { get; set; }
        public virtual FarmerDetail FarmerDetail { get; set; }
        public virtual InputSource InputSource { get; set; }
        public virtual VillageInfo VillageInfo { get; set; }
    }
}
