//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerConsumptionMapping
    {
        public int Id { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public Nullable<int> ConsumptionId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual FarmerConsumption FarmerConsumption { get; set; }
        public virtual FarmerDetail FarmerDetail { get; set; }
    }
}
