//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerLandMapping
    {
        public int Id { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public Nullable<int> LandTypeId { get; set; }
        public Nullable<int> OwnershipTypeId { get; set; }
        public Nullable<int> Acre { get; set; }
    
        public virtual FarmerDetail FarmerDetail { get; set; }
        public virtual FarmerLandType FarmerLandType { get; set; }
        public virtual LandOwnershipType LandOwnershipType { get; set; }
    }
}
