//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FarmerDetail()
        {
            this.FarmerConsumptionMappings = new HashSet<FarmerConsumptionMapping>();
            this.FarmerCropsMappings = new HashSet<FarmerCropsMapping>();
            this.FarmerDealerMappings = new HashSet<FarmerDealerMapping>();
            this.FarmerInputSourceMappings = new HashSet<FarmerInputSourceMapping>();
            this.FarmerLandMappings = new HashSet<FarmerLandMapping>();
            this.FarmerPesticesMappings = new HashSet<FarmerPesticesMapping>();
        }
    
        public int Id { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> DealerId { get; set; }
        public int FarmerTypeId { get; set; }
        public string FarmerFirstName { get; set; }
        public string FarmerMiddleName { get; set; }
        public string FarmerLastName { get; set; }
        public int PocketId { get; set; }
        public string FarmerAddress { get; set; }
        public string MobileNumber { get; set; }
        public string FertiCons { get; set; }
        public string DAP { get; set; }
        public string Urea { get; set; }
        public string Potash { get; set; }
        public Nullable<decimal> LandTotal { get; set; }
        public Nullable<decimal> IrrigatedFields { get; set; }
        public int SourceId { get; set; }
        public Nullable<decimal> DryLandFields { get; set; }
        public string FarmerDealerPesticides { get; set; }
        public string FarmerDealerFertilizer { get; set; }
        public string FarmerDealerSeeds { get; set; }
        public string SampleDemoDetails { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual DealerDetail DealerDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmerConsumptionMapping> FarmerConsumptionMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmerCropsMapping> FarmerCropsMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmerDealerMapping> FarmerDealerMappings { get; set; }
        public virtual FarmerTypeDetail FarmerTypeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmerInputSourceMapping> FarmerInputSourceMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmerLandMapping> FarmerLandMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmerPesticesMapping> FarmerPesticesMappings { get; set; }
    }
}
