//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAtargetDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAtargetDetail()
        {
            this.FAtargetVillageMappings = new HashSet<FAtargetVillageMapping>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FAid { get; set; }
        public Nullable<int> DealerId { get; set; }
        public Nullable<int> VillageId { get; set; }
    
        public virtual DealerDetail DealerDetail { get; set; }
        public virtual FAdetail FAdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAtargetVillageMapping> FAtargetVillageMappings { get; set; }
    }
}
