//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAuploadedDocumentDetail
    {
        public int Id { get; set; }
        public int FAid { get; set; }
        public int DocumentId { get; set; }
        public string UploadPath { get; set; }
        public bool IsActive { get; set; }
    
        public virtual FAdetail FAdetail { get; set; }
        public virtual FAdocumentType FAdocumentType { get; set; }
    }
}
