//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pesticide
    {
        public int Id { get; set; }
        public string PesticideName { get; set; }
        public Nullable<int> PesticideTypeId { get; set; }
    
        public virtual FarmerPesticideType FarmerPesticideType { get; set; }
    }
}
