//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PocketInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PocketInfo()
        {
            this.FAaddressDetails = new HashSet<FAaddressDetail>();
            this.PocketCropMappings = new HashSet<PocketCropMapping>();
            this.PocketFertilizerMappings = new HashSet<PocketFertilizerMapping>();
            this.PocketVillageMappings = new HashSet<PocketVillageMapping>();
        }
    
        public int PocketID { get; set; }
        public string PocketName { get; set; }
        public string PocaketPotentiallity { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> PocketStatusId { get; set; }
    
        public virtual DistrictInfo DistrictInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAaddressDetail> FAaddressDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PocketCropMapping> PocketCropMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PocketFertilizerMapping> PocketFertilizerMappings { get; set; }
        public virtual PocketStatu PocketStatu { get; set; }
        public virtual StateInfo StateInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PocketVillageMapping> PocketVillageMappings { get; set; }
    }
}
