//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PocketVillageMapping
    {
        public int Id { get; set; }
        public Nullable<int> PocketId { get; set; }
        public Nullable<int> SubDistrictId { get; set; }
        public Nullable<int> VillageId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual PocketInfo PocketInfo { get; set; }
        public virtual SubDistrictInfo SubDistrictInfo { get; set; }
        public virtual VillageInfo VillageInfo { get; set; }
    }
}
