//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PocketCropMapping
    {
        public int id { get; set; }
        public Nullable<int> PocketId { get; set; }
        public Nullable<int> CropId { get; set; }
    
        public virtual CropInfo CropInfo { get; set; }
        public virtual PocketInfo PocketInfo { get; set; }
    }
}
