//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure
    {
        public int ID1 { get; set; }
        public Nullable<double> ID { get; set; }
        public string Remarks { get; set; }
        public string Structure1 { get; set; }
    }
}
