//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupInfo
    {
        public int UserGroupID { get; set; }
        public int GroupID { get; set; }
        public int UserTypeID { get; set; }
    
        public virtual GroupInfo GroupInfo { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
